# Generated by Django 4.2.11 on 2024-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory_group',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='Income', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactioncategory_self',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='Income', max_length=20),
        ),
    ]
