# Generated by Django 4.2.11 on 2024-04-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0003_remove_user_account_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionCategory_group',
            new_name='TransactionCategoryGroup',
        ),
        migrations.RenameModel(
            old_name='TransactionCategory_self',
            new_name='TransactionCategorySelf',
        ),
        migrations.RenameModel(
            old_name='Transaction_group',
            new_name='TransactionGroup',
        ),
        migrations.RenameModel(
            old_name='Transaction_self',
            new_name='TransactionSelf',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
