# Generated by Django 4.2.11 on 2024-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0004_rename_transactioncategory_group_transactioncategorygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], default='Personal', max_length=20),
        ),
    ]
