# Generated by Django 4.2.11 on 2024-04-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0006_alter_user_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiongroup',
            old_name='transactionCategory_group',
            new_name='transaction_category',
        ),
        migrations.RenameField(
            model_name='transactionself',
            old_name='transaction_Category_self',
            new_name='transaction_category',
        ),
    ]
