# Generated by Django 4.2.11 on 2024-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0007_rename_transactioncategory_group_transactiongroup_transaction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategorygroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactioncategoryself',
            name='description',
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionself',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
