# Generated by Django 4.2.11 on 2024-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0008_remove_transactioncategorygroup_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/avatar/%Y/%m/%d/'),
        ),
    ]
