# Generated by Django 4.2.11 on 2024-04-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0010_freetimeoption_membership_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='options',
            field=models.ManyToManyField(related_name='option', to='QuanLyThuChi_app.freetimeoption'),
        ),
    ]
