# Generated by Django 4.2.11 on 2024-04-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0011_alter_survey_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetimeoption',
            name='date',
            field=models.DateField(),
        ),
    ]
