# Generated by Django 4.2.11 on 2024-05-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0012_alter_freetimeoption_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Member',
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='transaction_category',
            field=models.ForeignKey(on_delete=models.SET('Không có'), to='QuanLyThuChi_app.transactioncategorygroup'),
        ),
        migrations.AlterField(
            model_name='transactionself',
            name='transaction_category',
            field=models.ForeignKey(on_delete=models.SET('Không có'), to='QuanLyThuChi_app.transactioncategoryself'),
        ),
    ]
