# Generated by Django 4.2.11 on 2024-05-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0014_leader_delete_member_alter_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='transaction_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLyThuChi_app.transactioncategorygroup'),
        ),
        migrations.AlterField(
            model_name='transactionself',
            name='transaction_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLyThuChi_app.transactioncategoryself'),
        ),
    ]
