# Generated by Django 4.2.11 on 2024-05-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0016_member_delete_leader_alter_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongroup',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QuanLyThuChi_app.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionself',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
