# Generated by Django 4.2.11 on 2024-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0017_transactiongroup_group_transactionself_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategorygroup',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='Expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactioncategoryself',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='Expense', max_length=20),
        ),
    ]
