# Generated by Django 4.2.11 on 2024-05-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0019_remove_survey_group_remove_survey_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetimeoption',
            name='user',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='creator',
        ),
    ]
