# Generated by Django 4.2.11 on 2024-05-10 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0020_remove_freetimeoption_user_remove_survey_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetimeoption',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
