# Generated by Django 4.2.11 on 2024-05-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0021_freetimeoption_users_survey_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='option',
        ),
        migrations.AddField(
            model_name='freetimeoption',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QuanLyThuChi_app.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QuanLyThuChi_app.group'),
            preserve_default=False,
        ),
    ]
