# Generated by Django 4.2.11 on 2024-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0022_remove_survey_option_freetimeoption_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongroup',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
