# Generated by Django 4.2.11 on 2024-05-16 21:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0023_transactiongroup_accept'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='GroupMember',
        ),
        migrations.RemoveField(
            model_name='freetimeoption',
            name='users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.RemoveField(
            model_name='transactioncategorygroup',
            name='color',
        ),
        migrations.RemoveField(
            model_name='transactioncategoryself',
            name='color',
        ),
        migrations.AddField(
            model_name='freetimeoption',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='timestamp',
            field=models.DateField(default=datetime.date(2024, 5, 17)),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionself',
            name='timestamp',
            field=models.DateField(default=datetime.date(2024, 5, 17)),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=20),
        ),
    ]
