# Generated by Django 4.2.11 on 2024-05-19 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0024_rename_member_groupmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='timestamp',
            field=models.DateField(default=datetime.date(2024, 5, 19)),
        ),
        migrations.AlterField(
            model_name='transactionself',
            name='timestamp',
            field=models.DateField(default=datetime.date(2024, 5, 19)),
        ),
    ]
