# Generated by Django 4.2.11 on 2024-05-20 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0025_alter_transactiongroup_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='timestamp',
            field=models.DateField(default=datetime.date(2024, 5, 20)),
        ),
        migrations.AlterField(
            model_name='transactionself',
            name='timestamp',
            field=models.DateField(default=datetime.date(2024, 5, 20)),
        ),
    ]
