# Generated by Django 4.2.11 on 2024-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0026_alter_transactiongroup_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactionself',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
