# Generated by Django 4.2.11 on 2024-06-15 08:28

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0029_alter_transactioncategorygroup_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transactionself',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
