# Generated by Django 4.2.11 on 2024-06-15 09:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0031_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategorygroup',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='transactioncategoryself',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
