# Generated by Django 4.2.11 on 2024-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0032_alter_transactioncategorygroup_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategorygroup',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactioncategoryself',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategorygroup',
            unique_together={('name', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategoryself',
            unique_together={('name', 'user')},
        ),
    ]
